const router = require("express").Router()
const Controller = require("../../controllers/admin/admin")
const auth = require("../../middlewares/auth")

router.route("/addadmin").post(Controller.addadmin)
router.route("/adminlogin").post(Controller.adminlogin)
router.route("/adminmailsend").post(Controller.adminmailsend)
router.route("/adminforgotpassword").post(Controller.adminforgotpassword)
router.route("/getAllUser").get(Controller.getAllUser)
router.route("/getsingleUser/:id").get(Controller.getsingleUser)
router.route("/block/:id").post(Controller.block)
router.route("/unblock/:id").post(Controller.unblock)
router.route("/getblock").get(Controller.getblock)
router.route("/getunblock").get(Controller.getunblock)
router.route("/getinstructor").get(Controller.getinstructor)
router.route("/singleinstructor/:id").get(Controller.singleinstructor)
router.route("/getcourse").get(Controller.getcourse)
router.route("/getsinglecourse/:id").get(Controller.getsinglecourse)
router.route("/instructorblock/:id").post(Controller.instructorblock)
router.route("/instructorunblock/:id").post(Controller.instructorunblock)
router.route("/getinstructorblock").get(Controller.getinstructorblock)
router.route("/getinstructorunblock").get(Controller.getinstructorunblock)
router.route("/Courseapproved/:id").post(Controller.Courseapproved)
router.route("/Courserejected/:id").post(Controller.Courserejected)
router.route("/addfeaturedCourse/:id").post(Controller.addeaturedCourse)
router.route("/deletefeaturedCourse/:id").post(Controller.deletefeaturedCourse)


module.exports = router